// Regenerates the Resolve Timeline plugin's entrance/exit effect list from
// src/presets.ts's own ENTRANCE_NAMES/EXIT_NAMES/TEXT_ENTRANCE_NAMES arrays
// — run by install_resolve_plugin.bat (and safe to re-run any time by hand:
// `node tools/gen_resolve_effect_list.mjs`).
//
// WHY a generated file instead of importing presets.ts directly: the
// Timeline panel is a small, bundler-free Electron renderer script
// (com.motionist.timelinepanel/renderer.js) — it has no TypeScript
// toolchain to `import` a .ts file through. Previously it just hand-copied
// the two arrays as a literal comment-flagged "keep this in sync by hand"
// — which is exactly what silently drifted: this session added ~24 new
// effects to presets.ts and the plugin's copy was never touched, so none
// of them were reachable from inside Resolve. This script is the fix:
// presets.ts stays the one real source of truth, this just re-derives a
// plain-JS copy from it mechanically instead of relying on a human
// remembering to update a second, unrelated file.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const PRESETS_PATH = path.join(ROOT, "src", "presets.ts");
const OUT_PATH = path.join(ROOT, "resolve-plugin", "com.motionist.timelinepanel", "effect-names.generated.js");

const src = fs.readFileSync(PRESETS_PATH, "utf-8");

// Pulls the string literals out of `export const NAME: SomeType[] = [ ... ];`
// — a plain regex over presets.ts's own source text, not a real TS parse
// (no dependency needed for that). Good enough for a flat array of quoted
// identifiers, which is all these three ever are.
function extractArray(constName) {
  const re = new RegExp(`export const ${constName}\\s*:[^=]*=\\s*\\[([\\s\\S]*?)\\];`);
  const m = src.match(re);
  if (!m) throw new Error(`Could not find "export const ${constName}" in ${PRESETS_PATH}`);
  const names = [...m[1].matchAll(/"([^"]+)"/g)].map((x) => x[1]);
  if (!names.length) throw new Error(`"${constName}" matched but no quoted names were found inside it`);
  return names;
}

const entranceNames = extractArray("ENTRANCE_NAMES");
const textEntranceNames = extractArray("TEXT_ENTRANCE_NAMES");
const exitNames = extractArray("EXIT_NAMES");

const out = `// AUTO-GENERATED by tools/gen_resolve_effect_list.mjs from src/presets.ts —
// do not hand-edit; re-run that script (or install_resolve_plugin.bat,
// which runs it for you) after changing presets.ts's own effect lists.
const ENTRANCE_NAMES = ${JSON.stringify([...entranceNames, ...textEntranceNames])};
const EXIT_NAMES = ${JSON.stringify(exitNames)};
`;

fs.writeFileSync(OUT_PATH, out, "utf-8");
console.log(`Wrote ${entranceNames.length + textEntranceNames.length} entrance names and ${exitNames.length} exit names -> ${path.relative(ROOT, OUT_PATH)}`);
